version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  assembling:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Moscow
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
